
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1000
    target-branch: "develop"
    labels:
      - "composer"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1000
    target-branch: "develop"
    labels:
      - "npm"
      - "dependencies"